dist: xenial
sudo: true
language:
  - c
addons:
  apt:
    packages:
    - build-essential
    - git
    - autoconf
    - automake
    - libtool
    - pkg-config
    - python3
    - python3-pip
    - curl
    - gperf
    - flex
    - bison
    - gcc-arm-none-eabi

env:
  - >
      ZEPHYR_TOOLCHAIN_VARIANT=cross-compile
      CROSS_COMPILE=/usr/bin/arm-none-eabi-
      ZEPHYR_BASE=${TRAVIS_BUILD_DIR}
      ZEPHYRPROJECT=${ZEPHYR_BASE}/..
      PATH=${ZEPHYR_BASE}/scripts:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin

before_script:
  # Zephyr requires a fairly recent version of cmake and Ubuntu only has an older version in their repository
  # Also, Travis has a bunch of built-in tools in their xenial image, and cmake is one of them. It's incompatible, so is removed too.
  - sudo rm -Rf /usr/local/cmake-3.12.4/
  - sudo sh .ci/scripts/install-cmake.sh

  # Zephyr requires a fairly recent version of the Device Tree Compiler and Ubuntu only has an older version in their repository
  - sudo sh .ci/scripts/build-and-install-dtc.sh

  # Zephyr requires an arm bare-metal toolchain and does not (yet) support the toolchain in Ubuntu's repositories
  #- sudo sh .ci/scripts/install-gnuarmemb.sh

  # For CI, we need to build Zephyr wihtout west. The process is mostly documented here:
  # https://docs.zephyrproject.org/latest/getting_started/index.html
  # https://docs.zephyrproject.org/latest/guides/west/without-west.html#no-west
  # https://docs.zephyrproject.org/latest/guides/modules.html#without-west
  #
  # Locally, it's simple (with west):
  # pip3 install --user west
  # west init zephyrproject
  # cd zephyrproject
  # west update
  # pip3 install --user -r zephyr/scripts/requirements.txt
  # cd zephyr
  # source zephyr-env.sh
  # export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
  # export GNUARMEMB_TOOLCHAIN_PATH=/opt/arm/gcc-arm-none-eabi-8-2019-q3-update
  # west build -b cc1352r1_launchxl samples/hello_world
  #
  # However, without west, there are some tricky parts.
  # the checkout-modules.py script checks out all of the modules in the west.yml file, and also exports a list of (valid) modules
  # to ZEPHYR_MODULES.txt.
  - sudo python3 .ci/scripts/checkout-modules.py ${ZEPHYR_BASE}/west.yml ${ZEPHYRPROJECT} ${ZEPHYR_BASE}/ZEPHYR_MODULES.txt
  - sudo pip3 install --upgrade pip
  - pip3 install --user setuptools
  - pip3 install --user -r scripts/requirements.txt

script:
  - mkdir build
  - cmake -DZEPHYR_MODULES="`cat ZEPHYR_MODULES.txt`" -B build -DBOARD=cc1352r1_launchxl samples/subsys/greybus
  - make -j`nproc --all` -C build

notifications:
  email: false

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    file:
      - build/zephyr/zephyr.bin
      - build/zephyr/zephyr.elf
      - build/zephyr/zephyr.hex
      - build/zephyr/zephyr.lst
      - build/zephyr/zephyr.map
      - build/zephyr/zephyr.stat
    skip_cleanup: true
    on:
      tags: true
